# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('fullname', models.CharField(max_length=128)),
                ('contact_address', models.CharField(max_length=128)),
                ('due_date', models.DateField(verbose_name='date for customer delivery')),
                ('commission_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commissions.CommissionType')),
            ],
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='request',
            new_name='enquiry',
        ),
    ]
