# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_auto_20170404_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='commission_type',
        ),
        migrations.AlterField(
            model_name='commission',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commissions.Enquiry'),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
